fix

diff --git a/tools/download_ctftools b/tools/download_ctftools
--- a/tools/download_ctftools
+++ b/tools/download_ctftools
@@ -17,7 +17,7 @@
 
 MANTA_HOST="https://us-east.manta.joyent.com"
 MIN_PLATFORM="20181206T011455Z"
-LATEST="/Joyent_Dev/public/builds/SmartOS/ctftools/master/built.joyent_$MIN_PLATFORM/latest"
+MPATH="/Joyent_Dev/public/builds/SmartOS/ctftools/master/built.joyent_$MIN_PLATFORM"
 TARBALL="ctftools.tar.gz"
 
 if [[ -z $1 ]]; then
@@ -40,11 +40,12 @@ if [[ ! -f "$TMPDIR/$TARBALL" ]]; then
 	# Try to download the tarball from Manta.
 	#
 
-	URL="$(curl -sSf $MANTA_HOST/$LATEST)"
-	if [[ -z "$URL" ]]; then
-		printf "ERROR: failed to read $LATEST\n" >&2
+	LATEST="$(curl -sSf $MANTA_HOST/$MPATH/latest)"
+	if [[ -z "$LATEST" ]]; then
+		printf "ERROR: failed to read $MANTA_HOST/$MPATH/latest\n" >&2
 		exit 1
 	fi
+	URL="$MANTA_HOST/$LATEST/$TARBALL"
 
 	start_time=$SECONDS
 	rm -f "$TMPDIR/$TARBALL.tmp"
@@ -54,10 +55,9 @@ if [[ ! -f "$TMPDIR/$TARBALL" ]]; then
 			exit 1
 		fi
 
-		echo "Downloading $MANTA_HOST/$URL/$TARBALL"
+		echo "Downloading $URL"
 
-		if ! /usr/bin/curl -f -o "$TMPDIR/$TARBALL.tmp" \
-		    "$MANTA_HOST/$LATEST/$TARBALL"; then
+		if ! /usr/bin/curl -f -o "$TMPDIR/$TARBALL.tmp" "$URL"; then
 			printf "WARNING: download failure (retrying)\n" >&2
 			sleep 5
 			continue
