fix up download

diff --git a/tools/download_ctftools b/tools/download_ctftools
--- a/tools/download_ctftools
+++ b/tools/download_ctftools
@@ -15,12 +15,13 @@
 # job.
 #
 
-MANTA_URL='https://us-east.manta.joyent.com'
-BASE_PATH='/Joyent_Dev/public/ctftools/20181206T011455Z'
-TARBALL='ctftools.tar.gz'
+MANTA_HOST="https://us-east.manta.joyent.com"
+MIN_PLATFORM="20181206T011455Z"
+LATEST="/Joyent_Dev//public/builds/SmartOS/ctftools/master/built.joyent_$MIN_PLATFORM/latest"
+TARBALL="ctftools.tar.gz"
 
 if [[ -z $1 ]]; then
-	printf 'ERROR: usage: download_ctftools <destination dir>\n' 2>&1
+	printf "ERROR: usage: download_ctftools <destination dir>\n" 2>&1
 	exit 1
 fi
 
@@ -30,7 +31,7 @@ TMPDIR="$TOP/$CACHE_DIR"
 CTFDIR="$TOP/$CACHE_DIR/ctftools"
 
 if ! /usr/bin/mkdir -p "$TMPDIR"; then
-	printf 'ERROR: could not mkdir "%s"\n' "$TMPDIR" >&2
+	printf "ERROR: could not mkdir \"%s\"\n" "$TMPDIR" >&2
 	exit 1
 fi
 
@@ -38,31 +39,38 @@ if [[ ! -f "$TMPDIR/$TARBALL" ]]; then
 	#
 	# Try to download the tarball from Manta.
 	#
+
+	URL="$(curl -sSf $LATEST)"
+	if [[ -z "$URL" ]]; then
+		printf "ERROR: failed to read $LATEST\n" >&2
+		exit 1
+	fi
+
 	start_time=$SECONDS
 	rm -f "$TMPDIR/$TARBALL.tmp"
 	while :; do
 		if (( $SECONDS > start_time + 120 )); then
-			printf 'ERROR: timed out trying to download tools\n' >&2
+			printf "ERROR: timed out trying to download tools\n" >&2
 			exit 1
 		fi
 
-		echo "Downloading $MANTA_URL/$BASE_PATH/$TARBALL"
+		echo "Downloading $MANTA_HOST/$LATEST/$TARBALL"
 
 		if ! /usr/bin/curl -f -o "$TMPDIR/$TARBALL.tmp" \
-		    "$MANTA_URL/$BASE_PATH/$TARBALL"; then
-			printf 'WARNING: download failure (retrying)\n' >&2
+		    "$MANTA_HOST/$LATEST/$TARBALL"; then
+			printf "WARNING: download failure (retrying)\n" >&2
 			sleep 5
 			continue
 		fi
 
 		if ! /usr/bin/gzip -t "$TMPDIR/$TARBALL.tmp"; then
-			printf 'WARNING: download gzip invalid (retrying)\n' >&2
+			printf "WARNING: download gzip invalid (retrying)\n" >&2
 			sleep 5
 			continue
 		fi
 
 		if ! /usr/bin/mv "$TMPDIR/$TARBALL.tmp" "$TMPDIR/$TARBALL"; then
-			printf 'ERROR: could not move tarball into place\n' >&2
+			printf "ERROR: could not move tarball into place\n" >&2
 			exit 1
 		fi
 
@@ -74,7 +82,7 @@ fi
 # Extract the tarball
 #
 if ! /usr/bin/mkdir -p "$CTFDIR"; then
-	printf 'ERROR: could not mkdir "%s"\n' "$CTFDIR" >&2
+	printf "ERROR: could not mkdir \"%s\"\n" "$CTFDIR" >&2
 	exit 1
 fi
 
@@ -83,7 +91,7 @@ if ! cd "$CTFDIR"; then
 fi
 
 if ! /usr/bin/tar xfz "$TMPDIR/$TARBALL"; then
-	printf 'ERROR: could not extract tarball\n' >&2
+	printf "ERROR: could not extract tarball\n" >&2
 	exit 1
 fi
 
